Repository domeengine/dome, pull requests merged in 2020-10, with the labels that each got.

#96 added wren version
  src/main.c
Labels: hacktoberfest-accepted

#94 added Window.fps
  docs/modules/dome.md
  src/main.c
  src/modules/dome.c
  src/modules/dome.wren
  src/vm.c
Labels: hacktoberfest-accepted

#97 Allow lines of arbitrary thickness to be drawn
  docs/modules/graphics.md
  examples/geometry/main.wren
  src/engine.c
  src/modules/graphics.c
  src/modules/graphics.wren
  src/vm.c
Labels: Hacktoberfest

#106 Handle release bug fix
  src/main.c
Labels: bug

#107 mentioned the homebrew option for setup
  .gitignore
  docs/Gemfile
  docs/assets/css/style.scss
  docs/installation.md
Labels: Documentation
